version: '3'
services:
  web:
    image:
      aleczheng/license-frontend:v1
    ports:
      - '80:80'
    environment:
      - NGINX_BACK_END=backend
  backend:
    ports:
      - '8080:8080'
    image:
      aleczheng/license-backend:v1
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - '3306:3306'

