version: '3'
services:
  web:
    build:
      context: ./interests-front
      dockerfile: Dockerfile
    image:
      aleczheng/interests-front
    ports:
      - '8080:80'
    environment:
      - BACK_END=backend
  backend:
    build:
      context: ./interests-back
      dockerfile: Dockerfile.dev
    image:
      aleczheng/interests-back
