version: '3'
services:
  web:
    build:
      context: ./interests-front
      dockerfile: Dockerfile.dev
    image:
      aleczheng/interests-front
    ports:
      - '4200:4200'
    volumes:
      - /app/node_modules
      - './interests-front:/app'
  backend:
    build:
      context: ./interests-back
      dockerfile: Dockerfile.dev
    image:
      aleczheng/interests-front
