apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    component: backend
spec:
  containers:
    - name: backend
      image: aleczheng/interests-back
      ports:
        - containerPort: 80
